[package]
name = "vipchip"
version = "0.1.0"
authors = ["jdeeny"]
publish = false

[dependencies]
sdl2 = "0.20.1"
strfmt = "0.1.5"
chip8 = { git = "https://github.com/jdeeny/rust-chip8.git" , version = "0.1.0" }
